version: "3"

services:
  wda-plugin:
    image: caddy
    container_name: wda-plugin
    restart: unless-stopped
    ports:
      - '8901:80'
      - '8941:443'
    volumes:
      - caddy-config:/config
      - caddy-data:/data
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./app:/usr/share/caddy
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  caddy-config:
  caddy-data: